services:
  - type: web
    name: ai-for-education-backend
    env: python
    rootDir: back_end
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    plan: free

    autoDeploy: true
